name: Generate Blacklist
on: 
  workflow_dispatch:
  schedule:
  - cron: 0 1 * * *

env:
  TZ: Asia/Shanghai
  SMARTDNS_URL: https://github.com/pymumu/smartdns/releases/download/Release45/smartdns-x86_64
  SMARTDNS_PATH: /tmp/smartdns

jobs:
  Generate_Blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Python 3.9.x
        uses: actions/setup-python@main
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          python -m pip install --upgrade pip
          pip install -U requests tld tcping IPy dnspython
      
      - name: Setup SmartDNS
        run: |
          mkdir -p $SMARTDNS_PATH
          wget $SMARTDNS_URL -O $SMARTDNS_PATH/smartdns
          chmod +x $SMARTDNS_PATH/smartdns
          cp smartdns.conf $SMARTDNS_PATH/smartdns.conf
          nohup $SMARTDNS_PATH/smartdns -f -x -c $SMARTDNS_PATH/smartdns.conf > /dev/null 2>&1 &

      - name: Generate Blacklist
        run: |
          python blacklist.py
          rm -rf __pycache__

      - name: Commit Changes
        id: commit
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else
            echo "status=success" >> $GITHUB_OUTPUT
            git add .
            git config --local user.email "217heidai@gmail.com"
            git config --local user.name "217heidai"
            git commit -m "Updated at $(date)" -a
          fi
            
      - name: GitHub Push
        if: steps.commit.outputs.status == 'success' && !cancelled()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 30
          keep_minimum_runs: 10